# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/net/cremi/alerichard/Bureau/git projet"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/net/cremi/alerichard/Bureau/git projet"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/net/cremi/alerichard/Bureau/git projet/CMakeFiles" "/net/cremi/alerichard/Bureau/git projet/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/net/cremi/alerichard/Bureau/git projet/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 2048

# Build rule for target.
2048: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 2048
.PHONY : 2048

# fast build rule for target.
2048/fast:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/build
.PHONY : 2048/fast

control-grid.o: control-grid.c.o
.PHONY : control-grid.o

# target to build an object file
control-grid.c.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/control-grid.c.o
.PHONY : control-grid.c.o

control-grid.i: control-grid.c.i
.PHONY : control-grid.i

# target to preprocess a source file
control-grid.c.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/control-grid.c.i
.PHONY : control-grid.c.i

control-grid.s: control-grid.c.s
.PHONY : control-grid.s

# target to generate assembly for a file
control-grid.c.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/control-grid.c.s
.PHONY : control-grid.c.s

fonctions-sup.o: fonctions-sup.c.o
.PHONY : fonctions-sup.o

# target to build an object file
fonctions-sup.c.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/fonctions-sup.c.o
.PHONY : fonctions-sup.c.o

fonctions-sup.i: fonctions-sup.c.i
.PHONY : fonctions-sup.i

# target to preprocess a source file
fonctions-sup.c.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/fonctions-sup.c.i
.PHONY : fonctions-sup.c.i

fonctions-sup.s: fonctions-sup.c.s
.PHONY : fonctions-sup.s

# target to generate assembly for a file
fonctions-sup.c.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/fonctions-sup.c.s
.PHONY : fonctions-sup.c.s

grid.o: grid.c.o
.PHONY : grid.o

# target to build an object file
grid.c.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/grid.c.o
.PHONY : grid.c.o

grid.i: grid.c.i
.PHONY : grid.i

# target to preprocess a source file
grid.c.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/grid.c.i
.PHONY : grid.c.i

grid.s: grid.c.s
.PHONY : grid.s

# target to generate assembly for a file
grid.c.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/grid.c.s
.PHONY : grid.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... 2048"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... control-grid.o"
	@echo "... control-grid.i"
	@echo "... control-grid.s"
	@echo "... fonctions-sup.o"
	@echo "... fonctions-sup.i"
	@echo "... fonctions-sup.s"
	@echo "... grid.o"
	@echo "... grid.i"
	@echo "... grid.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

