# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeremym/Bureau/Projet2048

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeremym/Bureau/Projet2048

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeremym/Bureau/Projet2048/CMakeFiles /home/jeremym/Bureau/Projet2048/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeremym/Bureau/Projet2048/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 2048

# Build rule for target.
2048: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 2048
.PHONY : 2048

# fast build rule for target.
2048/fast:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/build
.PHONY : 2048/fast

#=============================================================================
# Target rules for targets named 2048G

# Build rule for target.
2048G: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 2048G
.PHONY : 2048G

# fast build rule for target.
2048G/fast:
	$(MAKE) -f CMakeFiles/2048G.dir/build.make CMakeFiles/2048G.dir/build
.PHONY : 2048G/fast

#=============================================================================
# Target rules for targets named A1_baltus_lejeune_richard_martin_slow

# Build rule for target.
A1_baltus_lejeune_richard_martin_slow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 A1_baltus_lejeune_richard_martin_slow
.PHONY : A1_baltus_lejeune_richard_martin_slow

# fast build rule for target.
A1_baltus_lejeune_richard_martin_slow/fast:
	$(MAKE) -f CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/build.make CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/build
.PHONY : A1_baltus_lejeune_richard_martin_slow/fast

#=============================================================================
# Target rules for targets named grid

# Build rule for target.
grid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grid
.PHONY : grid

# fast build rule for target.
grid/fast:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/build
.PHONY : grid/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
.PHONY : test1/fast

#=============================================================================
# Target rules for targets named test2

# Build rule for target.
test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test2
.PHONY : test2

# fast build rule for target.
test2/fast:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/build
.PHONY : test2/fast

control-grid.o: control-grid.c.o
.PHONY : control-grid.o

# target to build an object file
control-grid.c.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/control-grid.c.o
.PHONY : control-grid.c.o

control-grid.i: control-grid.c.i
.PHONY : control-grid.i

# target to preprocess a source file
control-grid.c.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/control-grid.c.i
.PHONY : control-grid.c.i

control-grid.s: control-grid.c.s
.PHONY : control-grid.s

# target to generate assembly for a file
control-grid.c.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/control-grid.c.s
.PHONY : control-grid.c.s

fonctions-sup.o: fonctions-sup.c.o
.PHONY : fonctions-sup.o

# target to build an object file
fonctions-sup.c.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/fonctions-sup.c.o
	$(MAKE) -f CMakeFiles/2048G.dir/build.make CMakeFiles/2048G.dir/fonctions-sup.c.o
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/fonctions-sup.c.o
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/fonctions-sup.c.o
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/fonctions-sup.c.o
.PHONY : fonctions-sup.c.o

fonctions-sup.i: fonctions-sup.c.i
.PHONY : fonctions-sup.i

# target to preprocess a source file
fonctions-sup.c.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/fonctions-sup.c.i
	$(MAKE) -f CMakeFiles/2048G.dir/build.make CMakeFiles/2048G.dir/fonctions-sup.c.i
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/fonctions-sup.c.i
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/fonctions-sup.c.i
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/fonctions-sup.c.i
.PHONY : fonctions-sup.c.i

fonctions-sup.s: fonctions-sup.c.s
.PHONY : fonctions-sup.s

# target to generate assembly for a file
fonctions-sup.c.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/fonctions-sup.c.s
	$(MAKE) -f CMakeFiles/2048G.dir/build.make CMakeFiles/2048G.dir/fonctions-sup.c.s
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/fonctions-sup.c.s
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/fonctions-sup.c.s
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/fonctions-sup.c.s
.PHONY : fonctions-sup.c.s

graphical-grid.o: graphical-grid.c.o
.PHONY : graphical-grid.o

# target to build an object file
graphical-grid.c.o:
	$(MAKE) -f CMakeFiles/2048G.dir/build.make CMakeFiles/2048G.dir/graphical-grid.c.o
.PHONY : graphical-grid.c.o

graphical-grid.i: graphical-grid.c.i
.PHONY : graphical-grid.i

# target to preprocess a source file
graphical-grid.c.i:
	$(MAKE) -f CMakeFiles/2048G.dir/build.make CMakeFiles/2048G.dir/graphical-grid.c.i
.PHONY : graphical-grid.c.i

graphical-grid.s: graphical-grid.c.s
.PHONY : graphical-grid.s

# target to generate assembly for a file
graphical-grid.c.s:
	$(MAKE) -f CMakeFiles/2048G.dir/build.make CMakeFiles/2048G.dir/graphical-grid.c.s
.PHONY : graphical-grid.c.s

grid.o: grid.c.o
.PHONY : grid.o

# target to build an object file
grid.c.o:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/grid.c.o
	$(MAKE) -f CMakeFiles/2048G.dir/build.make CMakeFiles/2048G.dir/grid.c.o
	$(MAKE) -f CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/build.make CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/grid.c.o
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/grid.c.o
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/grid.c.o
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/grid.c.o
.PHONY : grid.c.o

grid.i: grid.c.i
.PHONY : grid.i

# target to preprocess a source file
grid.c.i:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/grid.c.i
	$(MAKE) -f CMakeFiles/2048G.dir/build.make CMakeFiles/2048G.dir/grid.c.i
	$(MAKE) -f CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/build.make CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/grid.c.i
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/grid.c.i
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/grid.c.i
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/grid.c.i
.PHONY : grid.c.i

grid.s: grid.c.s
.PHONY : grid.s

# target to generate assembly for a file
grid.c.s:
	$(MAKE) -f CMakeFiles/2048.dir/build.make CMakeFiles/2048.dir/grid.c.s
	$(MAKE) -f CMakeFiles/2048G.dir/build.make CMakeFiles/2048G.dir/grid.c.s
	$(MAKE) -f CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/build.make CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/grid.c.s
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/grid.c.s
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/grid.c.s
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/grid.c.s
.PHONY : grid.c.s

strategy.o: strategy.c.o
.PHONY : strategy.o

# target to build an object file
strategy.c.o:
	$(MAKE) -f CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/build.make CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/strategy.c.o
.PHONY : strategy.c.o

strategy.i: strategy.c.i
.PHONY : strategy.i

# target to preprocess a source file
strategy.c.i:
	$(MAKE) -f CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/build.make CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/strategy.c.i
.PHONY : strategy.c.i

strategy.s: strategy.c.s
.PHONY : strategy.s

# target to generate assembly for a file
strategy.c.s:
	$(MAKE) -f CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/build.make CMakeFiles/A1_baltus_lejeune_richard_martin_slow.dir/strategy.c.s
.PHONY : strategy.c.s

test/test.o: test/test.c.o
.PHONY : test/test.o

# target to build an object file
test/test.c.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test/test.c.o
.PHONY : test/test.c.o

test/test.i: test/test.c.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.c.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test/test.c.i
.PHONY : test/test.c.i

test/test.s: test/test.c.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.c.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test/test.c.s
.PHONY : test/test.c.s

test/test2.o: test/test2.c.o
.PHONY : test/test2.o

# target to build an object file
test/test2.c.o:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test/test2.c.o
.PHONY : test/test2.c.o

test/test2.i: test/test2.c.i
.PHONY : test/test2.i

# target to preprocess a source file
test/test2.c.i:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test/test2.c.i
.PHONY : test/test2.c.i

test/test2.s: test/test2.c.s
.PHONY : test/test2.s

# target to generate assembly for a file
test/test2.c.s:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test/test2.c.s
.PHONY : test/test2.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... 2048"
	@echo "... 2048G"
	@echo "... A1_baltus_lejeune_richard_martin_slow"
	@echo "... edit_cache"
	@echo "... grid"
	@echo "... rebuild_cache"
	@echo "... test1"
	@echo "... test2"
	@echo "... control-grid.o"
	@echo "... control-grid.i"
	@echo "... control-grid.s"
	@echo "... fonctions-sup.o"
	@echo "... fonctions-sup.i"
	@echo "... fonctions-sup.s"
	@echo "... graphical-grid.o"
	@echo "... graphical-grid.i"
	@echo "... graphical-grid.s"
	@echo "... grid.o"
	@echo "... grid.i"
	@echo "... grid.s"
	@echo "... strategy.o"
	@echo "... strategy.i"
	@echo "... strategy.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
	@echo "... test/test2.o"
	@echo "... test/test2.i"
	@echo "... test/test2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

